/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IElectionRegistryDecryptionRecorder, IElectionRegistryDecryptionRecorderInterface } from "../../BU_PVP_1_DecryptionVerifier.sol/IElectionRegistryDecryptionRecorder.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "electionId",
        "type": "uint256"
      }
    ],
    "name": "recordDecryptionProofVerification",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IElectionRegistryDecryptionRecorder__factory {
    static readonly abi = _abi;
    static createInterface(): IElectionRegistryDecryptionRecorderInterface {
      return new Interface(_abi) as IElectionRegistryDecryptionRecorderInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IElectionRegistryDecryptionRecorder {
      return new Contract(address, _abi, runner) as unknown as IElectionRegistryDecryptionRecorder;
    }
  }
  