/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface BU_PVP_1_DecryptionVerifierInterface extends Interface {
    getFunction(nameOrSignature: "electionRegistry" | "groth16Verifier" | "verifyDecryptionProof"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DecryptionProofVerifiedOnChain"): EventFragment;

    encodeFunctionData(functionFragment: 'electionRegistry', values?: undefined): string;
encodeFunctionData(functionFragment: 'groth16Verifier', values?: undefined): string;
encodeFunctionData(functionFragment: 'verifyDecryptionProof', values: [BigNumberish, string, [BigNumberish, BigNumberish], [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]], [BigNumberish, BigNumberish], BigNumberish[]]): string;

    decodeFunctionResult(functionFragment: 'electionRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'groth16Verifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifyDecryptionProof', data: BytesLike): Result;
  }

  
    export namespace DecryptionProofVerifiedOnChainEvent {
      export type InputTuple = [electionId: BigNumberish, jobIdHash: BytesLike, proofHash: BytesLike, publicInputsHash: BytesLike, verifierContract: AddressLike];
      export type OutputTuple = [electionId: bigint, jobIdHash: string, proofHash: string, publicInputsHash: string, verifierContract: string];
      export interface OutputObject {electionId: bigint, jobIdHash: string, proofHash: string, publicInputsHash: string, verifierContract: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BU_PVP_1_DecryptionVerifier extends BaseContract {
    
    connect(runner?: ContractRunner | null): BU_PVP_1_DecryptionVerifier;
    waitForDeployment(): Promise<this>;

    interface: BU_PVP_1_DecryptionVerifierInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    electionRegistry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    groth16Verifier: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    verifyDecryptionProof: TypedContractMethod<
      [electionId: BigNumberish, jobId: string, a: [BigNumberish, BigNumberish], b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]], c: [BigNumberish, BigNumberish], input: BigNumberish[], ],
      [boolean],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'electionRegistry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'groth16Verifier'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'verifyDecryptionProof'): TypedContractMethod<
      [electionId: BigNumberish, jobId: string, a: [BigNumberish, BigNumberish], b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]], c: [BigNumberish, BigNumberish], input: BigNumberish[], ],
      [boolean],
      'nonpayable'
    >;

    getEvent(key: 'DecryptionProofVerifiedOnChain'): TypedContractEvent<DecryptionProofVerifiedOnChainEvent.InputTuple, DecryptionProofVerifiedOnChainEvent.OutputTuple, DecryptionProofVerifiedOnChainEvent.OutputObject>;

    filters: {
      
      'DecryptionProofVerifiedOnChain(uint256,bytes32,bytes32,bytes32,address)': TypedContractEvent<DecryptionProofVerifiedOnChainEvent.InputTuple, DecryptionProofVerifiedOnChainEvent.OutputTuple, DecryptionProofVerifiedOnChainEvent.OutputObject>;
      DecryptionProofVerifiedOnChain: TypedContractEvent<DecryptionProofVerifiedOnChainEvent.InputTuple, DecryptionProofVerifiedOnChainEvent.OutputTuple, DecryptionProofVerifiedOnChainEvent.OutputObject>;
    
    };
  }