/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IElectionRegistryTallyRecorder, IElectionRegistryTallyRecorderInterface } from "../../BU_PVP_1_TallyVerifier.sol/IElectionRegistryTallyRecorder.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "electionId",
        "type": "uint256"
      }
    ],
    "name": "recordTallyProofVerification",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IElectionRegistryTallyRecorder__factory {
    static readonly abi = _abi;
    static createInterface(): IElectionRegistryTallyRecorderInterface {
      return new Interface(_abi) as IElectionRegistryTallyRecorderInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IElectionRegistryTallyRecorder {
      return new Contract(address, _abi, runner) as unknown as IElectionRegistryTallyRecorder;
    }
  }
  