/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IGroth16Verifier, IGroth16VerifierInterface } from "../../BU_PVP_1_TallyVerifier.sol/IGroth16Verifier.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256[2]",
        "name": "a",
        "type": "uint256[2]"
      },
      {
        "internalType": "uint256[2][2]",
        "name": "b",
        "type": "uint256[2][2]"
      },
      {
        "internalType": "uint256[2]",
        "name": "c",
        "type": "uint256[2]"
      },
      {
        "internalType": "uint256[]",
        "name": "input",
        "type": "uint256[]"
      }
    ],
    "name": "verifyProof",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IGroth16Verifier__factory {
    static readonly abi = _abi;
    static createInterface(): IGroth16VerifierInterface {
      return new Interface(_abi) as IGroth16VerifierInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IGroth16Verifier {
      return new Contract(address, _abi, runner) as unknown as IGroth16Verifier;
    }
  }
  