/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { MockAlwaysValidGroth16Verifier, MockAlwaysValidGroth16VerifierInterface } from "../MockAlwaysValidGroth16Verifier.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint256[2]",
        "name": "",
        "type": "uint256[2]"
      },
      {
        "internalType": "uint256[2][2]",
        "name": "",
        "type": "uint256[2][2]"
      },
      {
        "internalType": "uint256[2]",
        "name": "",
        "type": "uint256[2]"
      },
      {
        "internalType": "uint256[]",
        "name": "",
        "type": "uint256[]"
      }
    ],
    "name": "verifyProof",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "pure",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b506102058061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610029575f3560e01c8063c32e370e1461002d575b5f5ffd5b61004760048036038101906100429190610116565b61005d565b60405161005491906101b6565b60405180910390f35b5f6001905095945050505050565b5f5ffd5b5f5ffd5b5f5ffd5b5f8190508260206002028201111561009257610091610073565b5b92915050565b5f819050826040600202820111156100b3576100b2610073565b5b92915050565b5f5ffd5b5f5ffd5b5f5f83601f8401126100d6576100d56100b9565b5b8235905067ffffffffffffffff8111156100f3576100f26100bd565b5b60208301915083602082028301111561010f5761010e610073565b5b9250929050565b5f5f5f5f5f61012086880312156101305761012f61006b565b5b5f61013d88828901610077565b955050604061014e88828901610098565b94505060c061015f88828901610077565b93505061010086013567ffffffffffffffff8111156101815761018061006f565b5b61018d888289016100c1565b92509250509295509295909350565b5f8115159050919050565b6101b08161019c565b82525050565b5f6020820190506101c95f8301846101a7565b9291505056fea2646970667358221220c9d9fc88328300bcb3e6464557a199ec060c81cf363e4acb43952e766d8e8c5964736f6c634300081c0033";

  
      type MockAlwaysValidGroth16VerifierConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MockAlwaysValidGroth16VerifierConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MockAlwaysValidGroth16Verifier__factory extends ContractFactory {
    
      constructor(...args: MockAlwaysValidGroth16VerifierConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<MockAlwaysValidGroth16Verifier & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MockAlwaysValidGroth16Verifier__factory {
      return super.connect(runner) as MockAlwaysValidGroth16Verifier__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MockAlwaysValidGroth16VerifierInterface {
      return new Interface(_abi) as MockAlwaysValidGroth16VerifierInterface;
    }
    
    override attach(address: string | Addressable): MockAlwaysValidGroth16Verifier {
      return super.attach(address) as MockAlwaysValidGroth16Verifier;
    }
  static connect(address: string, runner?: ContractRunner | null): MockAlwaysValidGroth16Verifier {
      return new Contract(address, _abi, runner) as unknown as MockAlwaysValidGroth16Verifier;
    }
  }

  
  