/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface BlockUrnaElectionInterface extends Interface {
    getFunction(nameOrSignature: "addParty" | "approveVoter" | "closeVoting" | "getPendingVoters" | "hasVoted" | "openRegistration" | "openVoting" | "owner" | "parties" | "partyCount" | "phase" | "rejectVoter" | "renounceOwnership" | "requestRegistration" | "totalVotes" | "transferOwnership" | "vote" | "votedPartyId" | "voterStatus"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "PartyAdded" | "PhaseChanged" | "RegistrationRequested" | "VoteCast" | "VoterApproved" | "VoterRejected"): EventFragment;

    encodeFunctionData(functionFragment: 'addParty', values: [string]): string;
encodeFunctionData(functionFragment: 'approveVoter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'closeVoting', values?: undefined): string;
encodeFunctionData(functionFragment: 'getPendingVoters', values?: undefined): string;
encodeFunctionData(functionFragment: 'hasVoted', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'openRegistration', values?: undefined): string;
encodeFunctionData(functionFragment: 'openVoting', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'parties', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'partyCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'phase', values?: undefined): string;
encodeFunctionData(functionFragment: 'rejectVoter', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'requestRegistration', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalVotes', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'vote', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'votedPartyId', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'voterStatus', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'addParty', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveVoter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closeVoting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPendingVoters', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasVoted', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'openRegistration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'openVoting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'parties', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'partyCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'phase', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rejectVoter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'requestRegistration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalVotes', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'votedPartyId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'voterStatus', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PartyAddedEvent {
      export type InputTuple = [partyId: BigNumberish, name: string];
      export type OutputTuple = [partyId: bigint, name: string];
      export interface OutputObject {partyId: bigint, name: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PhaseChangedEvent {
      export type InputTuple = [previousPhase: BigNumberish, newPhase: BigNumberish];
      export type OutputTuple = [previousPhase: bigint, newPhase: bigint];
      export interface OutputObject {previousPhase: bigint, newPhase: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RegistrationRequestedEvent {
      export type InputTuple = [voter: AddressLike];
      export type OutputTuple = [voter: string];
      export interface OutputObject {voter: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoteCastEvent {
      export type InputTuple = [voter: AddressLike, partyId: BigNumberish];
      export type OutputTuple = [voter: string, partyId: bigint];
      export interface OutputObject {voter: string, partyId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoterApprovedEvent {
      export type InputTuple = [voter: AddressLike];
      export type OutputTuple = [voter: string];
      export interface OutputObject {voter: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace VoterRejectedEvent {
      export type InputTuple = [voter: AddressLike];
      export type OutputTuple = [voter: string];
      export interface OutputObject {voter: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BlockUrnaElection extends BaseContract {
    
    connect(runner?: ContractRunner | null): BlockUrnaElection;
    waitForDeployment(): Promise<this>;

    interface: BlockUrnaElectionInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addParty: TypedContractMethod<
      [name: string, ],
      [void],
      'nonpayable'
    >
    

    
    approveVoter: TypedContractMethod<
      [voter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    closeVoting: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getPendingVoters: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    hasVoted: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    openRegistration: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    openVoting: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    parties: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint] & {name: string, voteCount: bigint }],
      'view'
    >
    

    
    partyCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    phase: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    rejectVoter: TypedContractMethod<
      [voter: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    requestRegistration: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    totalVotes: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    vote: TypedContractMethod<
      [partyId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    votedPartyId: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    voterStatus: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addParty'): TypedContractMethod<
      [name: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'approveVoter'): TypedContractMethod<
      [voter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'closeVoting'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getPendingVoters'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'hasVoted'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'openRegistration'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'openVoting'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'parties'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint] & {name: string, voteCount: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'partyCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'phase'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rejectVoter'): TypedContractMethod<
      [voter: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'requestRegistration'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalVotes'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'vote'): TypedContractMethod<
      [partyId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'votedPartyId'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'voterStatus'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PartyAdded'): TypedContractEvent<PartyAddedEvent.InputTuple, PartyAddedEvent.OutputTuple, PartyAddedEvent.OutputObject>;
getEvent(key: 'PhaseChanged'): TypedContractEvent<PhaseChangedEvent.InputTuple, PhaseChangedEvent.OutputTuple, PhaseChangedEvent.OutputObject>;
getEvent(key: 'RegistrationRequested'): TypedContractEvent<RegistrationRequestedEvent.InputTuple, RegistrationRequestedEvent.OutputTuple, RegistrationRequestedEvent.OutputObject>;
getEvent(key: 'VoteCast'): TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
getEvent(key: 'VoterApproved'): TypedContractEvent<VoterApprovedEvent.InputTuple, VoterApprovedEvent.OutputTuple, VoterApprovedEvent.OutputObject>;
getEvent(key: 'VoterRejected'): TypedContractEvent<VoterRejectedEvent.InputTuple, VoterRejectedEvent.OutputTuple, VoterRejectedEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PartyAdded(uint256,string)': TypedContractEvent<PartyAddedEvent.InputTuple, PartyAddedEvent.OutputTuple, PartyAddedEvent.OutputObject>;
      PartyAdded: TypedContractEvent<PartyAddedEvent.InputTuple, PartyAddedEvent.OutputTuple, PartyAddedEvent.OutputObject>;
    

      'PhaseChanged(uint8,uint8)': TypedContractEvent<PhaseChangedEvent.InputTuple, PhaseChangedEvent.OutputTuple, PhaseChangedEvent.OutputObject>;
      PhaseChanged: TypedContractEvent<PhaseChangedEvent.InputTuple, PhaseChangedEvent.OutputTuple, PhaseChangedEvent.OutputObject>;
    

      'RegistrationRequested(address)': TypedContractEvent<RegistrationRequestedEvent.InputTuple, RegistrationRequestedEvent.OutputTuple, RegistrationRequestedEvent.OutputObject>;
      RegistrationRequested: TypedContractEvent<RegistrationRequestedEvent.InputTuple, RegistrationRequestedEvent.OutputTuple, RegistrationRequestedEvent.OutputObject>;
    

      'VoteCast(address,uint256)': TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
      VoteCast: TypedContractEvent<VoteCastEvent.InputTuple, VoteCastEvent.OutputTuple, VoteCastEvent.OutputObject>;
    

      'VoterApproved(address)': TypedContractEvent<VoterApprovedEvent.InputTuple, VoterApprovedEvent.OutputTuple, VoterApprovedEvent.OutputObject>;
      VoterApproved: TypedContractEvent<VoterApprovedEvent.InputTuple, VoterApprovedEvent.OutputTuple, VoterApprovedEvent.OutputObject>;
    

      'VoterRejected(address)': TypedContractEvent<VoterRejectedEvent.InputTuple, VoterRejectedEvent.OutputTuple, VoterRejectedEvent.OutputObject>;
      VoterRejected: TypedContractEvent<VoterRejectedEvent.InputTuple, VoterRejectedEvent.OutputTuple, VoterRejectedEvent.OutputObject>;
    
    };
  }