/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BlockUrnaElection } from './BlockUrnaElection.js';
export * as factories from './factories/index.js';
export { BlockUrnaElection__factory } from './factories/BlockUrnaElection__factory.js';