/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace BU_PVP_1_ElectionRegistry {
      
    export type ElectionStruct = {manifestHash: BytesLike, authority: AddressLike, registryAuthority: AddressLike, coordinatorPubKey: BytesLike, phase: BigNumberish, createdAtBlock: BigNumberish}

    export type ElectionStructOutput = [manifestHash: string, authority: string, registryAuthority: string, coordinatorPubKey: string, phase: bigint, createdAtBlock: bigint] & {manifestHash: string, authority: string, registryAuthority: string, coordinatorPubKey: string, phase: bigint, createdAtBlock: bigint }
  
    }

  export interface BU_PVP_1_ElectionRegistryInterface extends Interface {
    getFunction(nameOrSignature: "archiveElection" | "ballotCount" | "closeRegistry" | "closeVoting" | "createElection" | "electionCount" | "finalizeProcessing" | "getElection" | "openAuditWindow" | "openRegistry" | "openVoting" | "owner" | "publishActa" | "publishBallot" | "publishResults" | "publishTallyProof" | "registryNullifierUsed" | "renounceOwnership" | "signup" | "signupCount" | "startProcessing" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "ActaPublished" | "BallotPublished" | "ElectionCreated" | "OwnershipTransferred" | "PhaseChanged" | "SignupRecorded" | "TallyProofPublished"): EventFragment;

    encodeFunctionData(functionFragment: 'archiveElection', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'ballotCount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'closeRegistry', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'closeVoting', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createElection', values: [BytesLike, AddressLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'electionCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'finalizeProcessing', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getElection', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'openAuditWindow', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'openRegistry', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'openVoting', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'publishActa', values: [BigNumberish, BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'publishBallot', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'publishResults', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'publishTallyProof', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'registryNullifierUsed', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'signup', values: [BigNumberish, BytesLike, BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'signupCount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'startProcessing', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'archiveElection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ballotCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closeRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closeVoting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createElection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'electionCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeProcessing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getElection', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'openAuditWindow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'openRegistry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'openVoting', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'publishActa', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'publishBallot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'publishResults', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'publishTallyProof', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registryNullifierUsed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'signup', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'signupCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startProcessing', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace ActaPublishedEvent {
      export type InputTuple = [electionId: BigNumberish, kind: BigNumberish, snapshotHash: BytesLike];
      export type OutputTuple = [electionId: bigint, kind: bigint, snapshotHash: string];
      export interface OutputObject {electionId: bigint, kind: bigint, snapshotHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace BallotPublishedEvent {
      export type InputTuple = [electionId: BigNumberish, ballotIndex: BigNumberish, ballotHash: BytesLike, ciphertext: BytesLike];
      export type OutputTuple = [electionId: bigint, ballotIndex: bigint, ballotHash: string, ciphertext: string];
      export interface OutputObject {electionId: bigint, ballotIndex: bigint, ballotHash: string, ciphertext: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ElectionCreatedEvent {
      export type InputTuple = [electionId: BigNumberish, manifestHash: BytesLike, authority: AddressLike, registryAuthority: AddressLike, coordinatorPubKey: BytesLike];
      export type OutputTuple = [electionId: bigint, manifestHash: string, authority: string, registryAuthority: string, coordinatorPubKey: string];
      export interface OutputObject {electionId: bigint, manifestHash: string, authority: string, registryAuthority: string, coordinatorPubKey: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PhaseChangedEvent {
      export type InputTuple = [electionId: BigNumberish, previousPhase: BigNumberish, newPhase: BigNumberish];
      export type OutputTuple = [electionId: bigint, previousPhase: bigint, newPhase: bigint];
      export interface OutputObject {electionId: bigint, previousPhase: bigint, newPhase: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SignupRecordedEvent {
      export type InputTuple = [electionId: BigNumberish, registryNullifier: BytesLike, votingPubKey: BytesLike];
      export type OutputTuple = [electionId: bigint, registryNullifier: string, votingPubKey: string];
      export interface OutputObject {electionId: bigint, registryNullifier: string, votingPubKey: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TallyProofPublishedEvent {
      export type InputTuple = [electionId: BigNumberish, proofHash: BytesLike, proofPayload: BytesLike];
      export type OutputTuple = [electionId: bigint, proofHash: string, proofPayload: string];
      export interface OutputObject {electionId: bigint, proofHash: string, proofPayload: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BU_PVP_1_ElectionRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): BU_PVP_1_ElectionRegistry;
    waitForDeployment(): Promise<this>;

    interface: BU_PVP_1_ElectionRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    archiveElection: TypedContractMethod<
      [electionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    ballotCount: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    closeRegistry: TypedContractMethod<
      [electionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    closeVoting: TypedContractMethod<
      [electionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createElection: TypedContractMethod<
      [manifestHash: BytesLike, registryAuthority: AddressLike, coordinatorPubKey: BytesLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    electionCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    finalizeProcessing: TypedContractMethod<
      [electionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getElection: TypedContractMethod<
      [electionId: BigNumberish, ],
      [BU_PVP_1_ElectionRegistry.ElectionStructOutput],
      'view'
    >
    

    
    openAuditWindow: TypedContractMethod<
      [electionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    openRegistry: TypedContractMethod<
      [electionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    openVoting: TypedContractMethod<
      [electionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    publishActa: TypedContractMethod<
      [electionId: BigNumberish, kind: BigNumberish, snapshotHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    publishBallot: TypedContractMethod<
      [electionId: BigNumberish, ciphertext: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    publishResults: TypedContractMethod<
      [electionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    publishTallyProof: TypedContractMethod<
      [electionId: BigNumberish, proofPayload: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    registryNullifierUsed: TypedContractMethod<
      [arg0: BigNumberish, arg1: BytesLike, ],
      [boolean],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    signup: TypedContractMethod<
      [electionId: BigNumberish, registryNullifier: BytesLike, votingPubKey: BytesLike, permitSig: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    signupCount: TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    startProcessing: TypedContractMethod<
      [electionId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'archiveElection'): TypedContractMethod<
      [electionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'ballotCount'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'closeRegistry'): TypedContractMethod<
      [electionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'closeVoting'): TypedContractMethod<
      [electionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createElection'): TypedContractMethod<
      [manifestHash: BytesLike, registryAuthority: AddressLike, coordinatorPubKey: BytesLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'electionCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'finalizeProcessing'): TypedContractMethod<
      [electionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getElection'): TypedContractMethod<
      [electionId: BigNumberish, ],
      [BU_PVP_1_ElectionRegistry.ElectionStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'openAuditWindow'): TypedContractMethod<
      [electionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'openRegistry'): TypedContractMethod<
      [electionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'openVoting'): TypedContractMethod<
      [electionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'publishActa'): TypedContractMethod<
      [electionId: BigNumberish, kind: BigNumberish, snapshotHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'publishBallot'): TypedContractMethod<
      [electionId: BigNumberish, ciphertext: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'publishResults'): TypedContractMethod<
      [electionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'publishTallyProof'): TypedContractMethod<
      [electionId: BigNumberish, proofPayload: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registryNullifierUsed'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BytesLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'signup'): TypedContractMethod<
      [electionId: BigNumberish, registryNullifier: BytesLike, votingPubKey: BytesLike, permitSig: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'signupCount'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'startProcessing'): TypedContractMethod<
      [electionId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'ActaPublished'): TypedContractEvent<ActaPublishedEvent.InputTuple, ActaPublishedEvent.OutputTuple, ActaPublishedEvent.OutputObject>;
getEvent(key: 'BallotPublished'): TypedContractEvent<BallotPublishedEvent.InputTuple, BallotPublishedEvent.OutputTuple, BallotPublishedEvent.OutputObject>;
getEvent(key: 'ElectionCreated'): TypedContractEvent<ElectionCreatedEvent.InputTuple, ElectionCreatedEvent.OutputTuple, ElectionCreatedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'PhaseChanged'): TypedContractEvent<PhaseChangedEvent.InputTuple, PhaseChangedEvent.OutputTuple, PhaseChangedEvent.OutputObject>;
getEvent(key: 'SignupRecorded'): TypedContractEvent<SignupRecordedEvent.InputTuple, SignupRecordedEvent.OutputTuple, SignupRecordedEvent.OutputObject>;
getEvent(key: 'TallyProofPublished'): TypedContractEvent<TallyProofPublishedEvent.InputTuple, TallyProofPublishedEvent.OutputTuple, TallyProofPublishedEvent.OutputObject>;

    filters: {
      
      'ActaPublished(uint256,uint8,bytes32)': TypedContractEvent<ActaPublishedEvent.InputTuple, ActaPublishedEvent.OutputTuple, ActaPublishedEvent.OutputObject>;
      ActaPublished: TypedContractEvent<ActaPublishedEvent.InputTuple, ActaPublishedEvent.OutputTuple, ActaPublishedEvent.OutputObject>;
    

      'BallotPublished(uint256,uint256,bytes32,bytes)': TypedContractEvent<BallotPublishedEvent.InputTuple, BallotPublishedEvent.OutputTuple, BallotPublishedEvent.OutputObject>;
      BallotPublished: TypedContractEvent<BallotPublishedEvent.InputTuple, BallotPublishedEvent.OutputTuple, BallotPublishedEvent.OutputObject>;
    

      'ElectionCreated(uint256,bytes32,address,address,bytes)': TypedContractEvent<ElectionCreatedEvent.InputTuple, ElectionCreatedEvent.OutputTuple, ElectionCreatedEvent.OutputObject>;
      ElectionCreated: TypedContractEvent<ElectionCreatedEvent.InputTuple, ElectionCreatedEvent.OutputTuple, ElectionCreatedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'PhaseChanged(uint256,uint8,uint8)': TypedContractEvent<PhaseChangedEvent.InputTuple, PhaseChangedEvent.OutputTuple, PhaseChangedEvent.OutputObject>;
      PhaseChanged: TypedContractEvent<PhaseChangedEvent.InputTuple, PhaseChangedEvent.OutputTuple, PhaseChangedEvent.OutputObject>;
    

      'SignupRecorded(uint256,bytes32,bytes)': TypedContractEvent<SignupRecordedEvent.InputTuple, SignupRecordedEvent.OutputTuple, SignupRecordedEvent.OutputObject>;
      SignupRecorded: TypedContractEvent<SignupRecordedEvent.InputTuple, SignupRecordedEvent.OutputTuple, SignupRecordedEvent.OutputObject>;
    

      'TallyProofPublished(uint256,bytes32,bytes)': TypedContractEvent<TallyProofPublishedEvent.InputTuple, TallyProofPublishedEvent.OutputTuple, TallyProofPublishedEvent.OutputObject>;
      TallyProofPublished: TypedContractEvent<TallyProofPublishedEvent.InputTuple, TallyProofPublishedEvent.OutputTuple, TallyProofPublishedEvent.OutputObject>;
    
    };
  }