/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'BU_PVP_1_DecryptionVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BU_PVP_1_DecryptionVerifier__factory>
getContractFactory(name: 'IElectionRegistryDecryptionRecorder', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IElectionRegistryDecryptionRecorder__factory>
getContractFactory(name: 'IGroth16DecryptionVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IGroth16DecryptionVerifier__factory>
getContractFactory(name: 'BU_PVP_1_ElectionRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BU_PVP_1_ElectionRegistry__factory>
getContractFactory(name: 'BU_PVP_1_TallyVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.BU_PVP_1_TallyVerifier__factory>
getContractFactory(name: 'IElectionRegistryTallyRecorder', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IElectionRegistryTallyRecorder__factory>
getContractFactory(name: 'IGroth16Verifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IGroth16Verifier__factory>
getContractFactory(name: 'Groth16DecryptionVerifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Groth16DecryptionVerifier__factory>
getContractFactory(name: 'Groth16Verifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Groth16Verifier__factory>
getContractFactory(name: 'MockAlwaysValidGroth16Verifier', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockAlwaysValidGroth16Verifier__factory>

  getContractAt(name: 'BU_PVP_1_DecryptionVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BU_PVP_1_DecryptionVerifier>
getContractAt(name: 'IElectionRegistryDecryptionRecorder', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IElectionRegistryDecryptionRecorder>
getContractAt(name: 'IGroth16DecryptionVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IGroth16DecryptionVerifier>
getContractAt(name: 'BU_PVP_1_ElectionRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BU_PVP_1_ElectionRegistry>
getContractAt(name: 'BU_PVP_1_TallyVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.BU_PVP_1_TallyVerifier>
getContractAt(name: 'IElectionRegistryTallyRecorder', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IElectionRegistryTallyRecorder>
getContractAt(name: 'IGroth16Verifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IGroth16Verifier>
getContractAt(name: 'Groth16DecryptionVerifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Groth16DecryptionVerifier>
getContractAt(name: 'Groth16Verifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Groth16Verifier>
getContractAt(name: 'MockAlwaysValidGroth16Verifier', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockAlwaysValidGroth16Verifier>

  deployContract(name: 'BU_PVP_1_DecryptionVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BU_PVP_1_DecryptionVerifier>
deployContract(name: 'IElectionRegistryDecryptionRecorder', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IElectionRegistryDecryptionRecorder>
deployContract(name: 'IGroth16DecryptionVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IGroth16DecryptionVerifier>
deployContract(name: 'BU_PVP_1_ElectionRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BU_PVP_1_ElectionRegistry>
deployContract(name: 'BU_PVP_1_TallyVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BU_PVP_1_TallyVerifier>
deployContract(name: 'IElectionRegistryTallyRecorder', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IElectionRegistryTallyRecorder>
deployContract(name: 'IGroth16Verifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IGroth16Verifier>
deployContract(name: 'Groth16DecryptionVerifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Groth16DecryptionVerifier>
deployContract(name: 'Groth16Verifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Groth16Verifier>
deployContract(name: 'MockAlwaysValidGroth16Verifier', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockAlwaysValidGroth16Verifier>

  deployContract(name: 'BU_PVP_1_DecryptionVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BU_PVP_1_DecryptionVerifier>
deployContract(name: 'IElectionRegistryDecryptionRecorder', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IElectionRegistryDecryptionRecorder>
deployContract(name: 'IGroth16DecryptionVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IGroth16DecryptionVerifier>
deployContract(name: 'BU_PVP_1_ElectionRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BU_PVP_1_ElectionRegistry>
deployContract(name: 'BU_PVP_1_TallyVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.BU_PVP_1_TallyVerifier>
deployContract(name: 'IElectionRegistryTallyRecorder', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IElectionRegistryTallyRecorder>
deployContract(name: 'IGroth16Verifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IGroth16Verifier>
deployContract(name: 'Groth16DecryptionVerifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Groth16DecryptionVerifier>
deployContract(name: 'Groth16Verifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Groth16Verifier>
deployContract(name: 'MockAlwaysValidGroth16Verifier', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockAlwaysValidGroth16Verifier>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  