/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MockAlwaysValidGroth16VerifierInterface extends Interface {
    getFunction(nameOrSignature: "verifyProof"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'verifyProof', values: [[BigNumberish, BigNumberish], [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]], [BigNumberish, BigNumberish], BigNumberish[]]): string;

    decodeFunctionResult(functionFragment: 'verifyProof', data: BytesLike): Result;
  }

  

  export interface MockAlwaysValidGroth16Verifier extends BaseContract {
    
    connect(runner?: ContractRunner | null): MockAlwaysValidGroth16Verifier;
    waitForDeployment(): Promise<this>;

    interface: MockAlwaysValidGroth16VerifierInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    verifyProof: TypedContractMethod<
      [arg0: [BigNumberish, BigNumberish], arg1: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]], arg2: [BigNumberish, BigNumberish], arg3: BigNumberish[], ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'verifyProof'): TypedContractMethod<
      [arg0: [BigNumberish, BigNumberish], arg1: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]], arg2: [BigNumberish, BigNumberish], arg3: BigNumberish[], ],
      [boolean],
      'view'
    >;

    

    filters: {
      
    };
  }